# LunarG Windows SDK 把 glslang CONFIG 文件套了一层，且 config 里的 lib/ 路径对不上。
# 不改 VSG、不加 submodule：用 VULKAN_SDK 里现成的 .lib，写一份最小 CONFIG 给
# find_package(glslang CONFIG)（thirdparty/vsg/CMakeLists.txt）。

if(NOT DEFINED ENV{VULKAN_SDK} OR "$ENV{VULKAN_SDK}" STREQUAL "")
    return()
endif()

file(TO_CMAKE_PATH "$ENV{VULKAN_SDK}" _aveVk)
if(EXISTS "${_aveVk}/Lib/${CMAKE_STATIC_LIBRARY_PREFIX}glslang${CMAKE_STATIC_LIBRARY_SUFFIX}")
    set(_aveVkLib "${_aveVk}/Lib")
elseif(EXISTS "${_aveVk}/lib/${CMAKE_STATIC_LIBRARY_PREFIX}glslang${CMAKE_STATIC_LIBRARY_SUFFIX}")
    set(_aveVkLib "${_aveVk}/lib")
else()
    return()
endif()
set(_aveVkInc "${_aveVk}/include")
if(NOT EXISTS "${_aveVkInc}/glslang/Public/ShaderLang.h")
    return()
endif()

function(ave_import_sdk_static target stem)
    if(TARGET ${target})
        return()
    endif()
    set(release "${_aveVkLib}/${CMAKE_STATIC_LIBRARY_PREFIX}${stem}${CMAKE_STATIC_LIBRARY_SUFFIX}")
    if(NOT EXISTS "${release}")
        message(WARNING "Vulkan SDK missing ${release}")
        return()
    endif()
    add_library(${target} STATIC IMPORTED)
    set_target_properties(${target} PROPERTIES
        IMPORTED_LOCATION "${release}"
        INTERFACE_INCLUDE_DIRECTORIES "${_aveVkInc}")
    set(debugLib "${_aveVkLib}/${CMAKE_STATIC_LIBRARY_PREFIX}${stem}d${CMAKE_STATIC_LIBRARY_SUFFIX}")
    if(EXISTS "${debugLib}")
        set_property(TARGET ${target} PROPERTY IMPORTED_LOCATION_DEBUG "${debugLib}")
    endif()
endfunction()

ave_import_sdk_static(glslang::OSDependent OSDependent)
ave_import_sdk_static(glslang::GenericCodeGen GenericCodeGen)
ave_import_sdk_static(glslang::MachineIndependent MachineIndependent)
ave_import_sdk_static(glslang::glslang glslang)
ave_import_sdk_static(glslang::SPIRV SPIRV)
ave_import_sdk_static(glslang::SPVRemapper SPVRemapper)
ave_import_sdk_static(glslang::glslang-default-resource-limits glslang-default-resource-limits)
ave_import_sdk_static(SPIRV-Tools SPIRV-Tools)
ave_import_sdk_static(SPIRV-Tools-opt SPIRV-Tools-opt)

if(NOT TARGET glslang::glslang)
    return()
endif()

set_property(TARGET glslang::MachineIndependent APPEND PROPERTY
    INTERFACE_LINK_LIBRARIES glslang::GenericCodeGen glslang::OSDependent)
set_property(TARGET glslang::glslang APPEND PROPERTY
    INTERFACE_LINK_LIBRARIES glslang::MachineIndependent SPIRV-Tools-opt)
set_property(TARGET glslang::SPIRV APPEND PROPERTY
    INTERFACE_LINK_LIBRARIES glslang::glslang glslang::SPVRemapper SPIRV-Tools-opt SPIRV-Tools)

set(_aveGlslangDir "${CMAKE_BINARY_DIR}/cmake/glslang")
file(MAKE_DIRECTORY "${_aveGlslangDir}")
file(WRITE "${_aveGlslangDir}/glslang-config.cmake"
    "# Generated by cmake/UseVulkanSdkGlslang.cmake — targets already imported.\n")
set(glslang_DIR "${_aveGlslangDir}" CACHE PATH "AeroVista wrapper: Vulkan SDK glslang" FORCE)

message(STATUS "glslang: Vulkan SDK ${_aveVkLib} (VSG ShaderCompiler)")
