name: Build and Test

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

permissions:
  contents: read

jobs:
  build-test:
    name: ${{ matrix.preset }}
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        preset: [ci-debug, ci-release]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Init submodules
        shell: bash
        run: |
          git config --global url."https://github.com/".insteadOf "git@github.com:"
          git submodule update --init --recursive

      - name: Setup Vulkan SDK
        uses: humbletim/setup-vulkan-sdk@v1.2.2
        with:
          version: 1.4.321.1

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Setup CMake
        uses: lukka/get-cmake@latest

      - name: Configure
        run: cmake --preset ${{ matrix.preset }}

      - name: Build
        run: cmake --build --preset ${{ matrix.preset }}

      - name: Test
        run: ctest --preset ${{ matrix.preset }} --output-on-failure
